#!/bin/bash -e
## Copyright 2025 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       https://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

# Run update for all wing level groups
# This is a convenience script to process all defined wing level groups.
# NOTE:
# It is assumed that each ".js" script in ./lib defines a single wing level group and nothing else!

# HISTORY:
# 14Sep23 MEG Fixed bug .js not being stripped from group name.
# 21Sep22 MEG bash syntax enhancments and clean-up
# 14Sep22 MEG Created.

# path to group scripts
#LIB=./lib
LIB='./lib/Wing'

# Get a list of all the group class files
files=($LIB/*.js)

# Remove groups superclass from the list of groups to process
#files=(${files[@]/$LIB\/Group\.js/})

# Update each group type, note the groups superclass Group.js is excluded
for f in "${files[@]}"; do
    class=$(basename "$f")
    group=${class%.js}
    echo "Updating group: $group"
    ./2updateGroup "$group"
done
