#!/bin/bash -e
## Copyright 2025 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       https://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

# Run update for all unit level groups
# This is a convenience script to process all defined unit level groups.
# NOTE:
# It is assumed that each ".js" script in ./lib/Unit defines a single unit level group and nothing else!

# HISTORY:
# 21Sep22 MEG bash syntax enhancements and clean-up
# 11Sep22 MEG Created

# path to all unit group class definitions
LIB=./lib/Unit

# get an array of all the unit class .js files in $LIB
files=($LIB/*.js)

# Now process each file as the group to update and call the update script
for f in "${files[@]}"; do
    t=$(basename "$f")
    grp=${t%.js}
    echo "Updating group: $grp"
    ./2updateUnitGroup "$grp"
done
