#!/bin/bash -e
## Copyright 2025 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       https://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.


# AllWingOfficersReport - produces two csv files one for all wing
# level officers (WingOfficers.csv) and a second for all
# unit level officers (UnitOfficers.csv)
# These files are then uploaded to the IT shared drive and used to
# update the "All Wing and Unit Officers" spreadsheet which is
# available to all wing members for viewing.

# History:
# 29Aug23 MEG Upgraded to mongosh, DB passed to script on command line.
# 25May21 MEG Created.

# source config file var's must be in same directory
. ./$(basename $0).conf

# source MongoDB credentials
. ./$CREDS

# Extract one csv file for each sheet and upload to the master spreadsheet
for s in "${SHEETS[@]}"; do
    echo sheet: "$s"
    mongosh --quiet -u "$USERID" -p "$PASSWD" --authenticationDatabase $DB $DB "$s".js >"$s".csv
    # upload sheet
    gam user $GUID update drivefile id "$FILEID" retainname localfile ./"$s".csv gsheet "$s"
done
