#!/bin/bash -e
# Prepare new mailing list of commanders, deputies and personnel officers
# for use is distribution of the reports

# History:
# 14Dec24 DJL Consolidate configuration files for single point changes.
# 29Aug23 MEG Upgraded to mongosh, DB passed to script on command line.
# 27Nov18 MEG Added mailinglist.include file.
# 20Oct18 MEG Remove names with pattern file.
# 05Oct18 MEG Created.
#

. ../getConfigValue

WING=$(getConfigValue "wing")
WORKDIR=$HOME/work/$WING/Reports
cd $WORKDIR

# Report generator MongoDB login credentials
CREDS=./reporter-creds
. $CREDS

# target database
DB=$WING

echo "Preparing New mailing list"
mongosh --quiet -u $USERID -p $PASSWD --authenticationDatabase $DB $DB CmdrsEmails.js

# export mailing list, add mailing list include file
mongoexport --db $DB -u $USERID -p $PASSWD --authenticationDatabase $DB -c reportEmailList --type csv -f primaryEmail|tail -n +2|cat - mailinglist.include|sort|uniq|grep -v -f mailing-list-exclude.pat >mailinglist
echo Total email addresses selected: $(cat mailinglist|wc -l)
echo Done.
