#!/bin/bash -e
# Prepare new member report for command staff.
# Then mail to the command staff mailing list.

# History:
# 29Aug23 MEG Upgraded to mongosh, DB passed to script on command line.
# 18Sep20 MEG Uploads files to shared drive, sends only links
# 06Jul19 MEG Correct sendemail message file syntax.
# 10Mar19 MEG Fixed options order parsing.
# 25Nov18 MEG Added options to change mailing list and message
# 24Oct18 MEG Added option to skip sending emails
# 02Oct18 MEG Created.
#

# Load config file
CONF=./$(basename $0).conf
if [ -f  $CONF ]; then
    . $CONF
else
    echo "Error: missing configuration file: $CONF"
    exit 1
fi

# Report generator MongoDB login credentials
. $CREDS

# Make date stamp
DATESTAMP=$(date +%Y%m%d)

#/bin/rm -f NewMembers-Report.csv

# make sure we are in the proper working directory
cd $WORKDIR

# cmd line options
OPTS="h?l:m:n"

USAGE="Usage: $(basename $0) [$OPTS]\n
\tCreate and mail new member report\n
\th|? - this help\n
\tl - mailing list ($MAILINGLIST)\n
\tm - new message or message file ($MESSAGE)\n
\tn - No email - skip sending report to mailing list\n
"

while getopts $OPTS o; do
    case $o in
	l) MAILINGLIST=OPTARG;;
	m) MESSAGE=OPTARG;;
	n) NOEMAIL="true";;
	h|?) echo -e $USAGE;exit 1;;
	*) echo -e $USAGE;exit 1;;
    esac
done
shift $(($OPTIND - 1))

echo "Preparing New members report"
fn=$DATESTAMP-NewMembers-Report.csv
mongosh --quiet -u $USERID -p $PASSWD --authenticationDatabase $DB \
	$DB NewMembersLastWeek.js >$fn
# Upload file to shared drive if there's anything to send (size gt 41 bytes)
if [ $( find ./$fn -type f -size +41c 2>/dev/null ) ]; then
    FILEID[$r]=$(gam user $ASUSER create drivefile \
		 teamdriveparent "$SHAREDDRIVE" \
		 teamdriveparentname "$DRIVEFOLDER" \
		 drivefilename "$fn" localfile "$fn" returnidonly)
    # clean-up
    /bin/rm $fn
    # if NOEMAIL is set skip sending report
    [[ -v NOEMAIL ]] && continue
    # Use GAM to email reports to commanders mailing list
    echo "Sent emails to list"
    gam sendemail file $MAILINGLIST subject "NHWG:Weekly New Members Report" $MESSAGE replace newmembers $FILEID
else
    echo "No report to send."
fi
echo Done.
