#!/bin/bash -eE
# Download and install a specified version of GAMADV-XTD3.
# GAM must have been previous installed and configured with project.
#
## Copyright 2020 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

# History:
# 22Mar25 MEG Switched to GAM Team GAM7 from GAMADV-XTD3 repo.
# 10Mar25 MEG $# = 0; print USAGE and exit with failure.
# 27Apr22 MEG $ARCH now calls cmd arch to get system architecture.
# 10Oct21 MEG -L takes precedence over specified version.
# 14Jul21 MEG -L now checks for latest, installs if not up to date.
# 15Dec20 MEG Added download only option.
# 15Dec20 MEG bail on failed download of archive.
# 14Dec20 MEG Ross fixed download uri, fixed to track.
# 14Dec20 MEG Ross changed download uri, fixed to track.
# 05Dec20 MEG Added install messages.
# 04Dec20 MEG Find GAMADV latest version for download
# 26Nov20 MEG Created.
#
function die () {
    echo "ERROR::$0:Download Failed."
    exit 1
}

OPTS="Dd:i:l:Lh?u:"

ARCH=$(arch)
DLPATH=$HOME/downloads
GLIBCVERSION=$(ldd --version|head -1|while read a b c d e;do echo $e;done)
#GAMURL="https://github.com/taers232c/GAMADV-XTD3/releases/download/v"
GAMURL="https://github.com/GAM-team/GAM/releases/download/v"
INSTALLDIR="/usr/local/bin"
USAGE="Usage: $(basename $0) [$OPTS] [\"gam-version-number\"]\n
Download and install GAM\n
\tD - Download only, do not install\n
\td - Download target path ($DLPATH)\n
\ti - Installation target directory ($INSTALLDIR)\n
\th|? - Help - this message\n

\tl - Glibc version ($GLIBCVERSION)\n
\tL - get GAM Latest version (takes precedence)\n
\tu - URL to GAM repo ($GAMURL)\n
Note: you must have privileges to copy to the install directory.\n
\tuse setfacl to set acls for user. Example: setfacl -m u:user1:rwx /usr/local/bin\n"

if [ $# = 0 ];then
    echo -e $USAGE
    exit 1
fi

while getopts $OPTS o; do
    case $o in
	d) DLPATH=$OPTARG;;
	D) DOWNLOADONLY=1;;
	i) INSTALLDIR=$OPTARG;;
	l) GLIBCVERSION="$OPTARG";;
	L) LATEST=1;;
	u) GAMURL="$OPTARG";;
	h?) echo -e $USAGE;exit 1;;
	*)  echo -e $USAGE;exit 1;;
    esac
done
shift $((OPTIND - 1 ))

if [ -v LATEST ]; then
    # Check for latest release, install only if gam not up to date
    # Depends on Ross's "checkrc" option for the gam version command.
    # This code replaces the more complex curl call that downloaded
    # the release page and looks for the latest release version in the page.
    if gam version checkrc &>/dev/null; then
	echo "GAM is up to date."
	exit 0
    else
	GAMVERSION=$(gam version checkrc|egrep "^[ \t]+Latest:"|(while read a b;do echo $b;done))
    fi
else
    GAMVERSION=$1
fi

ARCHIVE="gam-$GAMVERSION-linux-$ARCH-glibc$GLIBCVERSION.tar.xz"

if [ -v DEBUG ]; then
    echo ARCH: $ARCH
    echo DLPATH: $DLPATH
    echo INSTALLDIR: $INSTALLDIR
    echo GAMVERSION: $GAMVERSION
    echo ARCHIVE: $ARCHIVE
    echo URL: $GAMURL
fi


pushd $DLPATH &>/dev/null

# attempt to download GAM archive
echo "Downloading GAM..."
echo Download: "$GAMURL$GAMVERSION/$ARCHIVE"

/usr/bin/curl -sL "$GAMURL$GAMVERSION/$ARCHIVE" --output $ARCHIVE
#echo ret: $?
SIZE=$(stat -c%s $ARCHIVE)
echo SIZE: $SIZE
(($SIZE > 1000000)) || die
#trap "echo ERROR:Download $GAMURL$GAMVERSION/$ARCHIVE failed." ERR
#wget -q "$GAMURL$GAMVERSION/$ARCHIVE" > $ARCHIVE

# Check for download only
# If DOWNLOANDONLY bail out and leave it for the user
if [ -v DOWNLOADONLY ]; then
    echo "Downloaded: $ARCHIVE"
    popd &>/dev/null
    exit 0
fi

echo "Installing: $GAMVERSION"
# unpack archive
tar Jxf $ARCHIVE

# you must have access privilege to do the copy to system directories
# See man setfacl
cp -pr $DLPATH/gam7/* $INSTALLDIR
echo "Done."

popd &>/dev/null
