#!/bin/bash -e
# Download and install a specified version of GAMADV-XTD3.
# GAM must have been previous installed and configured with project.
#
## Copyright 2020 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

# History:
# 15Dec20 MEG added download only option.
# 15Dec20 MEG exit if archive did not download.
# 14Dec20 MEG Ross fixed download uri, fixed to track.
# 14Dec20 MEG Ross changed download uri, fixed to track.
# 05Dec20 MEG Added install messages.
# 04Dec20 MEG Find GAMADV latest version for download
# 26Nov20 MEG Created.
#

OPTS="Dd:i:l:Lh?u:"

ARCH=$(uname -p)
DLPATH=$HOME/downloads
GLIBCVERSION=$(ldd --version|head -1|while read a b c d e;do echo $e;done)
GAMURL="https://github.com/taers232c/GAMADV-XTD3/releases/download/v"
INSTALLDIR="/usr/local/bin"
USAGE="Usage: $(basename $0) [$OPTS] [\"gam-version-number\"]\n
Download and install GAMADV-XTD3\n
\tD - Download only, do not install\n
\td - Download target path ($DLPATH)\n
\ti - Installation target directory ($INSTALLDIR)\n
\th|? - Help - this message\n
\tl - Glibc version ($GLIBCVERSION)\n
\tL - get GAMADV-XTD3 Latest version\n
\tu - URL to GAMADVX repo ($GAMURL)\n
Note: you must have privileges to copy to the install directory.\n
\tuse setfacl to set acls for user.\n"

while getopts $OPTS o; do
    case $o in
	d) DLPATH=$OPTARG;;
	D) DOWNLOADONLY=1;;
	i) INSTALLDIR=$OPTARG;;
	l) GLIBCVERSION="$OPTARG";;
	L) LATEST=1;;
	u) GAMURL="$OPTARG";;
	h?) echo -e $USAGE;exit 1;;
	*)  echo -e $USAGE;exit 1;;
    esac
done
shift $((OPTIND - 1 ))

if [ -v LATEST ]; then
    GAMVERSION=$(curl -s https://github.com/taers232c/GAMADV-XTD3|egrep ">GAM ([0-9]+\.[0-9]{2}\.[0-9]{2})"|(while read a b c d e f g h i;do echo $h;done)|sed -e 's/<\/span>//')
elif [ $# = 1 ]; then
    GAMVERSION=$1
else
    echo "Error: no GAM version specified"
    echo -e $USAGE
    exit 1
fi

ARCHIVE="gamadv-xtd3-$GAMVERSION-linux-$ARCH-glibc$GLIBCVERSION.tar.xz"

pushd $DLPATH &>/dev/null

# attempt to download GAM archive
curl -sL "$GAMURL$GAMVERSION/$ARCHIVE" --output $ARCHIVE
SIZE=$( wc -c < $ARCHIVE )
if (( SIZE < 1000000 )); then
    echo "ERROR:Download failed."
    exit 1
fi

# Check for download only
if [ -v DOWNLOADONLY ]; then
    echo "Downloaded: $ARCHIVE"
    popd &>/dev/null
    exit 0
fi

echo "Installing: $GAMVERSION"
# unpack archive
tar Jxf $ARCHIVE

# you must have access privilege to do the copy to system directories
cp $DLPATH/gamadv-xtd3/* $INSTALLDIR
echo "Done."

popd &>/dev/null
