#!/bin/bash -e
# Download and install a specified version of GAMADV-XTD3
#
# History:
# 04Dec20 MEG Find GAMADV latest version for download
# 26Nov20 MEG Created.
#

OPTS="d:i:l:Lh?u:"

ARCH=$(uname -p)
DLPATH=$HOME/downloads
#GLIBCVERSION=$(ldd --version | gawk '/^ldd/ {print $NF;}')
GLIBCVERSION=$(ldd --version|head -1|while read a b c d e;do echo $e;done)
GAMURL="https://github.com/taers232c/GAMADV-XTD3/releases/download/v"
INSTALLDIR="/usr/local/bin"
USAGE="Usage: $(basename $0) [$OPTS] [\"gam-version-number\"]\n
\td - Download target path ($DLPATH)\n
\ti - Installation target directory ($INSTALLDIR)\n
\th|? - Help - this message\n
\tl - Glibc version ($GLIBCVERSION)\n
\tL - get GAMADV-XTD3 Latest version\n
\tu - URL to GAMADVX repo ($GAMURL)\n
Note: you must have privileges to copy to the install directory.\n
\tuse setfacl to set acls for user.\n"

while getopts $OPTS o; do
    case $o in
	d) DLPATH=$OPTARG;;
	i) INSTALLDIR=$OPTARG;;
	l) GLIBCVERSION="$OPTARG";;
	L) LATEST=1;;
	u) GAMURL="$OPTARG";;
	h?) echo -e $USAGE;exit 1;;
	*)  echo -e $USAGE;exit 1;;
    esac
done
shift $((OPTIND - 1 ))

if [ -v LATEST ]; then
    GAMVERSION=$(curl -s https://github.com/taers232c/GAMADV-XTD3|egrep ">GAM ([0-9]+\.[0-9]{2}\.[0-9]{2})"|(while read a b c d e f g h i;do echo $h;done)|sed -e 's/<\/span>//')
elif [ $# = 1 ]; then
    GAMVERSION=$1
else
    echo "Error: no GAM version specified"
    echo -e $USAGE
    exit 1
fi

ARCHIVE="gamadv-xtd3-$GAMVERSION-linux-$ARCH-glibc$GLIBCVERSION.tar.xz"

pushd $DLPATH &>/dev/null

# attempt to download GAM archive
#wget -q "$GAMURL$GAMVERSION/$ARCHIVE"
curl -sL "$GAMURL$GAMVERSION/$ARCHIVE" --output $ARCHIVE

# unpack archive
tar Jxvf $ARCHIVE

# you must have access privilege to do the copy to system directories
cp $DLPATH/gamadv-xtd3/* $INSTALLDIR

popd &>/dev/null
