#!/bin/bash -e
## Copyright 2025 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       https://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.


#
# Populate a share drive directory structure
# from the supplied CSV file.  Uses advanced GAM.
# CSV file must be in this form:
# Header row:
# Path
# # Path ::= <topFolderName/...>
# There may be many paths, one per row
# EXAMPLE CSV:
# Path
# A/B/C/Last
# A/B/B 1/b last

# NOTES:
# 1. $3 shared drive name must be unique GAM will grab the first matching name.
# 2. Folder names on the drive must be unique, GAM will only match the first one.

# History:
# 03May23 MEG Created
#

USAGE="$(basename $0) CSVfile adminEmail sharedDriveName
Create folder hierarchies on the named shared drive
from the CSV file using the admin specified."

if (( $# < 3 )); then
    echo -e "$USAGE"
    exit 1
fi

gam loop "$1" gam user $2 create drivefolderpath fullpath "/SharedDrives/$3/~~Path~~"
