#!/bin/bash -e
## Copyright 2025 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       https://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.


# Issue a GAM command to reset a users password
#
# History:
# 27Aug20 MEG Make password random.
# 24Apr20 MEG Fixed quoting bug in email subject
# 10Apr20 MEG Created.

# Path to email message template
EMAIL_TEMPLATE="../Templates/Password_reset_template.html"

USAGE="Usage: $basename $0 user notify\n
\tuser - The domain user account\n
\tnotify- The email address to recevie the reset notification\n
NOTE: You must have admin privileges on G Suite to run this command.\n
"

if (( $# < 2 )); then
   echo -e $USAGE
   exit 1
fi

# issue gam password reset command
gam update user $1 password random changepassword true notify $2 subject "\"Password reset notification\"" file $EMAIL_TEMPLATE html true
