#!/bin/bash -e
## Copyright 2022 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

# Purpose: Download all NHWG groups and group members as a CSV
# convert to JSON and import into MongoDB.
#
# History:
# 02Jun22 MEG Move config var's to a config file
# 16Oct21 MEG use cigroups to get create & update time for group members
# 04Sep19 MEG Simplified moved to flat csv file group collection.
# 27Jun19 MEG Download option added.
# 09May18 MEG Created.

CONF=./importGroups.conf

# import config var's
. $CONF

# MongoDB credentials
CREDS=./importercreds

. $CREDS

OPTS='Dh'

USAGE="USAGE $(basename $0) [$OPTS]\n
\tImport Google Groups file: $GROUPSFILE\n
\tD - Download before importing\n
\th|? - this help message\n"

while getopts $OPTS o; do
    case $o in
	D) D="yes";;
	h|?) echo -e $USAGE;exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [ -v D ]; then
# Download Google groups as CSV from Google
    gam redirect csv $GROUPSFILE print cigroup-members &>/dev/null
fi

# import groups into MongoDB
$IMPORT --db $DB --authenticationDatabase=$DB --username=$MONGOUID \
	--password=$MONGOPASS --collection GoogleGroups --drop --type csv \
	--headerline --file $GROUPSFILE

# After import convert "createTime" and "updateTime" strings to ISO dates
mongo $DB -u $MONGOUID -p $MONGOPASS --authenticationDatabase=$DB --eval \
      'db.getCollection("GoogleGroups").updateMany( {}, [{ $set: { createTime: { $dateFromString: { dateString: "$createTime"}}}},{ $set: { updateTime: { $dateFromString: { dateString: "$updateTime"}}}}]);'
