#!/bin/bash -e
## Copyright 2025 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       https://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

# Batch script to create mims jobs to update NHWG member accounts
# This script creates all the weekly jobs.
# Add new jobs as classes to mims.py, then add class name to TASK var.

# HISTORY:
# 07Dec24 DJL Consolidate configuration files for single point changes.
# 09Aug18 MEG Added New Cadets to TASK list.
# 24Jun18 MEG Check table import failure and abort
# 10Jun18 MEG Specify job list on Command line.
# 19Apr18 MEG Created.

. getConfigValue

echo $(getConfigValue "wing") "MIMS Member create update batch jobs."

cd $(getConfigValue "mimsSourceTopDir")

# the list of mims jobs to be run
TASK="NewSeniors NewCadets Expired PurgeMembers UnSuspend"

# check for flag that table import failed and abort
if [ -f "IMPORTFAILED" ]; then
   echo "CAPWATCH tables import failed, not continuing with job creation."
   echo "Please check previous stages for failures."
   exit 1
fi
   
if [ $# -gt 0 ]; then
    TASK=$@
fi

for t in $TASK; do
    echo "Running create job: "$t
    ./mims.py $t
    echo "Done. Check job and log for errors."
done

echo "Jobs will be run tomorrow!"
echo "Check for accuracy!"
echo "Check jobs for files and correctness before releasing."
echo "PurgeMember jobs are on HOLD by default."
echo "List of pending jobs:"
ls -l job/*.job
echo "Done."
