#!/bin/bash
## Copyright 2017 Marshall E. Giguere
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.


# Extract tables from CAPWATCH file and convert them to something
# mongoimport can live with. Extracts tables listed in TABLES and 
# converts them to CSV files appropriate for monogimport. User may
# substitute tables to be extracted.
#
# History:
# 18Jul17 MEG Removed option to change archiver.
# 13Jul17 MEG User may now substitute tables form cmd line.
# 12Jul17 MEG Converts dates to MicroSoft SQL format.
# 03Jul17 MEG Convert date fields to Oracle UTC format.
# 23Jun17 MEG Created.
#
# Archiver
ARC=unzip

# Default Zip file
ZIP=$HOME/Downloads/CAPWATCH.zip

# Default DB
DB=NHWG

# Options
OPTS="h?z:"

# List of Tables to extract
TABLES="Commanders Member MbrContact MbrAddresses MbrAchievements DutyPosition"

# Help message
USAGE="Usage: $(basename $0) [$OPTS] [table table...]\n
\tExtract tables from CAPWATCH archive and filter.\n
\tz - zip file ($ZIP)\n
\tTABLES - $TABLES"

# Process options
while getopts $OPTS o; do
    case $o in
	a) ARC=$OPTARG;;
	z) ZIP=$OPTARG;;
	h|?) echo -e $USAGE;exit 1;;
	*) echo -e $USAGE;exit 1;;
    esac
done
shift $(( $OPTIND - 1 ))

# Check for substituted list of tables
if [ $# -ge 1 ]; then
    TABLES=$@
fi

# Extract each table, strip header line,
# convert dates to MicroSoft SQL format and write to a csv file
for t in $TABLES; do
    $ARC -p $ZIP $t.txt|tail -n +2|sed -r -e 's/(")([0-9]+\/[0-9]{2}\/[0-9]{4})(")/\2 05:00:00/g' >$t.csv
done
