#!/bin/bash -e
#
# Import CAPWATCH tables into MongoDB.
# Note: Files must have been preprocessed with getTables before importing.
#
# History:
# 03Jul17 MEG Created.
#
# Database to connect to
DB=NHWG
# Mongo import tool
IMP=/usr/bin/mongoimport
# CAPWATCH table to import
TABLES="Member MbrContact MbrAddresses MbrAchievements DutyPosition"
# Path to column type def's for each table
TYPEPATH=./MIMS
UID=MIMSImporter
PASS=mimsimporter

for t in $TABLES; do
    $IMP --db $DB  --collection $t --drop --type csv --columnsHaveTypes \
	--fieldFile $TYPEPATH/$t.types --file $t.csv
done
